# Use root/example as user/password credentials
version: '3.1'

services:

  mongo-test:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  # nats-test:
  #   image: nats:latest
  #   restart: always
  #   ports:
  #     - 4222:4222
  #   depends_on:
  #     - "mongo-test"
